include:
  - board: nrfmicro_13
    shield: settings_reset
    artifact-name: reset

  - board: nrfmicro_13
    shield: cornix_left
    snippet: studio-rpc-usb-uart
    artifact-name: cornix_left

  - board: nrfmicro_13
    shield: cornix_right
    artifact-name: cornix_right
